from colorama import Fore, init


def display():
    init(autoreset=True)
    pb_girl = [
        f"       .                       ",
        f"       |`.                     ",
        f"       ;  `.                   ",
        f"       ; :. \\           __     ",
        f'       ; ; \\ \\      .--"  \\    ',
        f"       ; ;  ; ;     :      \\   ",
        f"       ; ;  : :     ; ;     ;  ",
        f"       ' :   ; ;    ;::     :  ",
        f"        \\ \\  : ;--.-;; l     ; ",
        f"         \\ \\  ;:    :;//'-.__: ",
        f"         /\\ \\ ::____:::-\\      ",
        f'        /  ).:+\'""""""""=\\     ',
        f'       :_,=""     /"-.    ;    ',
        f"       ;\"       .'    `.  |    ",
        f"      :      .-^=    ==.\\ |    ",
        f'      |  _.-".gp      gp:;:    ',
        f"      ;    /  $$      $$;: ;   ",
        f"     :    :  `--      --:  |   ",
        f"     ;    ;\\        ,   '  |   ",
        f"    :    :  \\    {Fore.RED}  _{Fore.YELLOW}   /   :   ",
        f"    ;    |   `.  {Fore.RED} `-'{Fore.YELLOW} /     ;  ",
        f"   :     :    :`-.__.'      |  ",
        f"   ;          ;     :       |  ",
        f"  :     ...._/      '.__..  |  ",
        f"  ;   .'                  \\ ;  ",
        f" :   /                   _ Y   ",
        f" ;  :         {Fore.RED}.g$$p.    d$$+.  ",
        f" ;  ;     :{Fore.RED}.g$$$$$$$$p.d$$$$$b ",
        f" :  :     :{Fore.RED}$$$$$$$$$$$T$$$$$$$;",
        f"  \\  ;    {Fore.RED};$$$$S$$$$$$$S$$$$$P ",
        f"   `.|    |{Fore.RED}$$$$S$$$$$$$S$$$$P  ",
        f"     |    |{Fore.RED}T$$$$$SSSSS$$$$$$   ",
        f"     :    | {Fore.RED}`T$$$$$$$$$$$$$;   ",
        f"      ;   |  {Fore.RED} $$$$$$$$$$$$$    ",
        f"      |   :   {Fore.RED}$$$$$$$$$$$$;    ",
        f"      :    ; {Fore.RED}d$$$$$$$$$$$$;    ",
        f"      |    {Fore.RED}:d$$$$$$$$$$$$$$    ",
        f'      ;    :{Fore.RED}"^T$$$$$$$$$$$$b   ',
        f"     :     ;   {Fore.RED}`T$$$$$$$$$$P{Fore.YELLOW};  ",
        f"     ;    :      {Fore.RED}`T$$$$$$$P {Fore.YELLOW}:  ",
        f"     |    ;        {Fore.RED}T$$$$$P   {Fore.YELLOW}; ",
        f"     |   :          {Fore.RED}T$$P'    {Fore.YELLOW}; ",
        f"     :   ;           {Fore.RED}$'      {Fore.YELLOW}: ",
        f"    ._;__;           :       : ",
        f"    ; ;  ;           |       : ",
        f"    :_L__:           |       ; ",
        f"    .'    ;          |       ; ",
        f"  .'      :          |      :  ",
        f" :/ _.-.  :;         |      |  ",
        f" /.'    \\ |:         |      ;  ",
        f"//  bug  ;| ;        |     :   ",
        f"`        `' :        |     |   ",
        f"             ;       |     ;   ",
        f"             :       |    :    ",
        f"              ;      |    |    ",
        f"              :      :    ;    ",
        f"              :    _.'-   ;    ",
        f"              ;     /:    :    ",
        f"             /     / ;     ;   ",
        f"            /     :  ;     :   ",
        f"           :      ;  ;     :   ",
        f"           ;     :  :      :   ",
        f"          :      ;  :      ;   ",
        f"          ;     :   ;     :    ",
        f"         :      ;   ;     ;    ",
        f"         ;     :    ;    :     ",
        f"         ;     ;    ;    ;     ",
        f"         ;    :     ;   :      ",
        f"         |    ;     ;   ;      ",
        f"         |   :      ;  :       ",
        f"         |   ;      ;  ;       ",
        f"         :  :       :  ;       ",
        f"         ;  :       :  :       ",
        f"        :    ,      ;   ;      ",
        f"        ;    ;      ;   :      ",
        f"       :     :      :    ;     ",
        f"       :     ;      {Fore.BLUE}:b__d$     ",
        f"       {Fore.BLUE}$b   d$       $$$$$     ",
        f"       {Fore.BLUE}:$bgd$;        T$P'     ",
        f"        {Fore.BLUE}T$$$P                  ",
        f"         {Fore.BLUE}'\"'                  ",
    ]
    for line in pb_girl:
        print(Fore.YELLOW+ line)